### ISSUE TITLE
Add a method to exclude certain files from triggering a reload

### ISSUE THREAD

**Issue by gashcrumb** [davidB/livereload-jvm#1]
We've started using this today in our project https://github.com/hawtio/hawtio, works really well!

It'd be nice though if there was a way to exclude files, even via a simple callback function whenever a change is detected so we can determine whether or not a reload should be triggered.  This is handy for cases like ours where we've got typescript to compile, right now a reload is triggered when you save a typescript file, and again when the typescript compile writes the resulting javascript, being able to exclude .ts files would sort this.  Thanks!

**Comment by davidB** [comment]
Do you use the tool as library or as command line ?
I'll see how to add the feature (else you call do a pull request).

**Comment by gashcrumb** [comment]
Hey!  We're using it as a library at the moment.  I'll probably not get to working on it for a few, but can submit a pull request in a couple days if you don't get to it first...  Thanks!

**Comment by davidB** [comment]
The change is deployed with version 0.2.0-SNAPHOT at https://oss.sonatype.org/content/repositories/snapshots

**Comment by gashcrumb** [comment]
Ah cool, thanks!  Are you planning on doing another release anytime soon?

**Comment by davidB** [comment]
I'm updating the pom.xml (plugin's version, require maven 3, add your name in contributor)
When it'll be DONE, I'll deploy the release (~24H00 to be available on central + mirror)

**Comment by gashcrumb** [comment]
Okay great.  Thank you!

**Comment by davidB** [comment]
0.2.0 deployed on central repository.

**Comment by gashcrumb** [comment]
Excellent, that was quick!
